version: '3.8'

services:
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 127.0.0.1 --port 8008 --reload"
    volumes:
      - .:/app
    ports:
      - 8008:8008
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

volumes:
  postgres_data: